name: Stage the app

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read/write
      pull-requests: read/write

    if: contains(github.event.pull_request.labels.*.name, 'stage')
